sudo: required
dist: trusty
python: "3.6"
services:
  - docker
env:
  global:
    - IMAGE_NAME=sylvance/kuns-orbit
    - secret: "my-secret-squared"

before_script:
  - docker pull "${IMAGE_NAME}:master" || true
script:
  - docker build --pull --cache-from "${IMAGE_NAME}:master" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:master"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}-master"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:master" && docker push "${IMAGE_NAME}:${git_sha}-master"
  on:
    branch: master
